### ISSUE TITLE
Please correct spelling of source files

### ISSUE THREAD

**Issue by wildptr** [fzyz999/crazy_coder#1]
s/comipler/compiler/g

**Comment by Harinlen** [comment]
Well, this project is nearly abandon. 
We start a new project named Cuties, you can find it here: https://github.com/Kreogist/Cuties
But due to our lazyness, this project hasn't been updated for months :( and we hoped that one day we can rewrite this project.

**Comment by wildptr** [comment]
well... then, so be it :)
